### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by tarlepp**

### CODE REVIEW

**Comment by Dylan-DPC-zz** [comment]
Thanks but no interest in some of these changes.

**Comment by tarlepp** [comment]
Can you tell me what is wrong with those modifications? those follow PSR2 rules

**Comment by Dylan-DPC-zz** [comment]
1) I don't see the need of using strict_types at the top
2) i prefer self return type over the class name as it is makes it more obvious that it is returning the same class
3) Not a fan of each parameter on each line for `send` method. I know it may be listed in PSR2. 
4) I don't see the need for a trailing slash before `json_decode`. 
5) Interface shouldn't return the concrete class because the whole point of the abstraction is to ensure that concrete class can be swapped while abiding to the interface. 

You may have valid reasons for some of these but I still feel there is no need for it now. Thanks anyway :)

**Comment by tarlepp** [comment]
imho wrong kind of response to PR, you should address those "problems" and not just close PR. I see that you have done this same with other PR's aswell - so see you later...

**Comment by Dylan-DPC-zz** [comment]
Meh.. I don't want to keep the PR dragging on. I could highlight the problems and then you will change them which will go on back and forth and also have to keep track if anyone else makes any changes. Some of these issues have already been addressed by another PR. So thanks :)

**Pull request closed without merging**
